theme: jekyll-theme-minimal #minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", , "dark", "dirt", "neon", "mint", "plum" "sunrise"
title: Abhilash Gupta
description: |
  Research Assistant, CISPA, 
  Saarland University,
  Saarbrücken, Germany, 66123.
  abhilash0272@gmail.com
logo: files/me.jpg
